### ISSUE TITLE
Ajuste del API CRUD por cambio del modelo de datos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/admisiones_crud#8]
Se debe relizar un ajuste del API CRUD movitivo al ajuste del modelo de datos establecido en el [modelo](https://github.com/udistrital/campus_cliente/issues/174), el API debe cumplir con los siguientes requerimientos:

- [x] El crud debe cumplir con los lineamientos de la Oficina asesora de sistemas.
- [x] El crud debe contar con el refactor, para que las respuestas sean en formato Json.
- [x] Comprobar si la Api funciona correctamente con Swagger.

**Comment by fabianbarreto02** [comment]
Se ajusta  el API CRUD para el modelo de datos de adminiciones, queda pendiente revision por parte @mafeave.

**Comment by fabianbarreto02** [comment]
La rama en la que se trabajo es modeloV7

**Comment by mafeave** [comment]
Hace falta definir pipeline de acuerdo al ejemplo: https://github.com/udistrital/titan_api_crud/blob/desarrollo/.drone.yml

**Comment by fabianbarreto02** [comment]
se define el pipeline del api siguiendo el ejemplo establecido, para esto se agregan los archivos:
- Dockerfile
- .dockerignore
- entrypoint.sh
- imagedef.json
- main_test.go
- sonar-project.properties

Nota aclaratoria: el pipeline esta definido con un push a la rama master o develop, la rama desarrollada se llamo modeloV7

**Comment by mafeave** [comment]
Validados los ajustes se da por finalizada la tarea.
